apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  ippen.space/variant: production

bases:
  - ../../base/

# https://github.com/kubernetes-sigs/kustomize/issues/1493
patches:
  - path: pullpolicytoifnotpresent.yaml
    target:
      kind: Deployment