apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  ippen.space/team: uiwi
  ippen.space/service-owner: acasado
  app.kubernetes.io/managed-by: kustomize

commonLabels:
  app.kubernetes.io/part-of: cdp

bases:
  - cdp-kafka-userjourney-query

resources:
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml

namespace: uiwi

namePrefix: cdp-
