apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-boot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spring-boot
subjects:
  - kind: ServiceAccount
    name: spring-boot