apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  app.kubernetes.io/name: cdp-kafka-userjourney-query

commonLabels:
  app.kubernetes.io/component: cdp-kafka-userjourney-query

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml